export interface Problem {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  completed: boolean;
  phase: number;
}

export interface Category {
  id: string;
  name: string;
  problems: Problem[];
  color: string;
}

export interface Stage {
  number: number;
  name: string;
  description: string;
  categories: Category[];
}

const problemsData: Stage[] = [
  {
    number: 1,
    name: 'Foundations',
    description: 'Build raw pattern recognition.',
    categories: [
      {
        id: 'arrays-hashing',
        name: 'Arrays & Hashing',
        color: 'bg-blue-50 border-blue-200',
        problems: [
          {
            id: '1',
            title: 'Two Sum',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
          {
            id: '2',
            title: 'Contains Duplicate',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
          {
            id: '3',
            title: 'Valid Anagram',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
          {
            id: '4',
            title: 'Group Anagrams',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '5',
            title: 'Top K Frequent Elements',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '6',
            title: 'Product of Array Except Self',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '7',
            title: 'Longest Consecutive Sequence',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
        ],
      },
      {
        id: 'two-pointers',
        name: 'Two Pointers',
        color: 'bg-purple-50 border-purple-200',
        problems: [
          {
            id: '8',
            title: 'Valid Palindrome',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
          {
            id: '9',
            title: 'Two Sum II (sorted)',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '10',
            title: '3Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '11',
            title: 'Container With Most Water',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '12',
            title: 'Remove Duplicates from Sorted Array',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
        ],
      },
      {
        id: 'sliding-window',
        name: 'Sliding Window — Level 1',
        color: 'bg-amber-50 border-amber-200',
        problems: [
          {
            id: '13',
            title: 'Best Time to Buy and Sell Stock',
            difficulty: 'Easy',
            completed: false,
            phase: 1,
          },
          {
            id: '14',
            title: 'Longest Substring Without Repeating Characters',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '15',
            title: 'Longest Repeating Character Replacement',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '16',
            title: 'Permutation in String',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
          {
            id: '17',
            title: 'Minimum Size Subarray Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 1,
          },
        ],
      },
    ],
  },
  {
    number: 2,
    name: 'Stack, Binary Search, Linked List',
    description: 'Master fundamental data structures.',
    categories: [
      {
        id: 'stack',
        name: 'Stack',
        color: 'bg-red-50 border-red-200',
        problems: [
          {
            id: '18',
            title: 'Valid Parentheses',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '19',
            title: 'Min Stack',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '20',
            title: 'Daily Temperatures',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '21',
            title: 'Next Greater Element I',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '22',
            title: 'Evaluate Reverse Polish Notation',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'binary-search',
        name: 'Binary Search',
        color: 'bg-green-50 border-green-200',
        problems: [
          {
            id: '23',
            title: 'Binary Search',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '24',
            title: 'Search Insert Position',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '25',
            title: 'Search in Rotated Sorted Array',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '26',
            title: 'Find Minimum in Rotated Sorted Array',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '27',
            title: 'Koko Eating Bananas',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'linked-list',
        name: 'Linked List',
        color: 'bg-indigo-50 border-indigo-200',
        problems: [
          {
            id: '28',
            title: 'Reverse Linked List',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '29',
            title: 'Merge Two Sorted Lists',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '30',
            title: 'Linked List Cycle',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '31',
            title: 'Remove Nth Node From End',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '32',
            title: 'Reorder List',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
    ],
  },
  {
    number: 3,
    name: 'Trees (FAANG FAVORITE ZONE)',
    description: 'Spend serious time here.',
    categories: [
      {
        id: 'trees',
        name: 'Binary Trees',
        color: 'bg-teal-50 border-teal-200',
        problems: [
          {
            id: '33',
            title: 'Invert Binary Tree',
            difficulty: 'Easy',
            completed: false,
            phase: 3,
          },
          {
            id: '34',
            title: 'Maximum Depth of Binary Tree',
            difficulty: 'Easy',
            completed: false,
            phase: 3,
          },
          {
            id: '35',
            title: 'Diameter of Binary Tree',
            difficulty: 'Medium',
            completed: false,
            phase: 3,
          },
          {
            id: '36',
            title: 'Balanced Binary Tree',
            difficulty: 'Easy',
            completed: false,
            phase: 3,
          },
          {
            id: '37',
            title: 'Same Tree',
            difficulty: 'Easy',
            completed: false,
            phase: 3,
          },
          {
            id: '38',
            title: 'Subtree of Another Tree',
            difficulty: 'Easy',
            completed: false,
            phase: 3,
          },
          {
            id: '39',
            title: 'Lowest Common Ancestor (BST)',
            difficulty: 'Medium',
            completed: false,
            phase: 3,
          },
          {
            id: '40',
            title: 'Binary Tree Level Order Traversal',
            difficulty: 'Medium',
            completed: false,
            phase: 3,
          },
          {
            id: '41',
            title: 'Right Side View',
            difficulty: 'Medium',
            completed: false,
            phase: 3,
          },
          {
            id: '42',
            title: 'Count Good Nodes',
            difficulty: 'Medium',
            completed: false,
            phase: 3,
          },
        ],
      },
    ],
  },
  {
    number: 4,
    name: 'Backtracking',
    description: 'Master recursive problem solving.',
    categories: [
      {
        id: 'backtracking',
        name: 'Backtracking',
        color: 'bg-orange-50 border-orange-200',
        problems: [
          {
            id: '43',
            title: 'Subsets',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '44',
            title: 'Combination Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '45',
            title: 'Permutations',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '46',
            title: 'Subsets II',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '47',
            title: 'Word Search',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '48',
            title: 'Palindrome Partitioning',
            difficulty: 'Medium',
            completed: false,
            phase: 4,
          },
          {
            id: '49',
            title: 'N-Queens',
            difficulty: 'Hard',
            completed: false,
            phase: 4,
          },
        ],
      },
    ],
  },
  {
    number: 5,
    name: 'Heap / Priority Queue',
    description: 'Learn efficient data organization.',
    categories: [
      {
        id: 'heap',
        name: 'Heap / Priority Queue',
        color: 'bg-pink-50 border-pink-200',
        problems: [
          {
            id: '50',
            title: 'Kth Largest Element in Array',
            difficulty: 'Medium',
            completed: false,
            phase: 5,
          },
          {
            id: '51',
            title: 'Top K Frequent Elements (heap version)',
            difficulty: 'Medium',
            completed: false,
            phase: 5,
          },
          {
            id: '52',
            title: 'Find Median from Data Stream',
            difficulty: 'Hard',
            completed: false,
            phase: 5,
          },
          {
            id: '53',
            title: 'Merge K Sorted Lists',
            difficulty: 'Hard',
            completed: false,
            phase: 5,
          },
          {
            id: '54',
            title: 'Task Scheduler',
            difficulty: 'Medium',
            completed: false,
            phase: 5,
          },
        ],
      },
    ],
  },
  {
    number: 6,
    name: 'Greedy',
    description: 'Make optimal local choices.',
    categories: [
      {
        id: 'greedy',
        name: 'Greedy',
        color: 'bg-lime-50 border-lime-200',
        problems: [
          {
            id: '55',
            title: 'Maximum Subarray (Kadane)',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '56',
            title: 'Jump Game',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '57',
            title: 'Jump Game II',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '58',
            title: 'Gas Station',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '59',
            title: 'Merge Intervals',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '60',
            title: 'Non-overlapping Intervals',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
          {
            id: '61',
            title: 'Partition Labels',
            difficulty: 'Medium',
            completed: false,
            phase: 6,
          },
        ],
      },
    ],
  },
  {
    number: 7,
    name: 'Dynamic Programming (CRITICAL)',
    description: 'Take this slowly.',
    categories: [
      {
        id: 'dp-basics',
        name: 'DP Basics',
        color: 'bg-cyan-50 border-cyan-200',
        problems: [
          {
            id: '62',
            title: 'Climbing Stairs',
            difficulty: 'Easy',
            completed: false,
            phase: 7,
          },
          {
            id: '63',
            title: 'Min Cost Climbing Stairs',
            difficulty: 'Easy',
            completed: false,
            phase: 7,
          },
          {
            id: '64',
            title: 'House Robber',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '65',
            title: 'House Robber II',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '66',
            title: 'Coin Change',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '67',
            title: 'Maximum Product Subarray',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
        ],
      },
      {
        id: 'dp-intermediate',
        name: 'DP Intermediate',
        color: 'bg-fuchsia-50 border-fuchsia-200',
        problems: [
          {
            id: '68',
            title: 'Longest Increasing Subsequence',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '69',
            title: 'Longest Common Subsequence',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '70',
            title: 'Word Break',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '71',
            title: 'Combination Sum IV',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '72',
            title: 'Decode Ways',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '73',
            title: 'Unique Paths',
            difficulty: 'Medium',
            completed: false,
            phase: 7,
          },
          {
            id: '74',
            title: 'Edit Distance',
            difficulty: 'Hard',
            completed: false,
            phase: 7,
          },
        ],
      },
    ],
  },
  {
    number: 8,
    name: 'Graphs',
    description: 'Must master BFS/DFS thinking.',
    categories: [
      {
        id: 'graphs',
        name: 'Graphs',
        color: 'bg-violet-50 border-violet-200',
        problems: [
          {
            id: '75',
            title: 'Number of Islands',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '76',
            title: 'Clone Graph',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '77',
            title: 'Max Area of Island',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '78',
            title: 'Pacific Atlantic Water Flow',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '79',
            title: 'Course Schedule',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '80',
            title: 'Course Schedule II',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '81',
            title: 'Graph Valid Tree',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '82',
            title: 'Number of Connected Components',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
          {
            id: '83',
            title: 'Network Delay Time (Dijkstra)',
            difficulty: 'Medium',
            completed: false,
            phase: 8,
          },
        ],
      },
    ],
  },
  {
    number: 9,
    name: 'Advanced / FAANG Differentiators',
    description: 'Do these after everything above feels comfortable.',
    categories: [
      {
        id: 'advanced',
        name: 'Advanced Problems',
        color: 'bg-rose-50 border-rose-200',
        problems: [
          {
            id: '84',
            title: 'LRU Cache',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '85',
            title: 'Trapping Rain Water',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '86',
            title: 'Sliding Window Maximum',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '87',
            title: 'Minimum Window Substring',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '88',
            title: 'Serialize and Deserialize Binary Tree',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '89',
            title: 'Word Ladder',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '90',
            title: 'Alien Dictionary',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '91',
            title: 'Longest Increasing Path in Matrix',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
          {
            id: '92',
            title: 'Median of Two Sorted Arrays',
            difficulty: 'Hard',
            completed: false,
            phase: 9,
          },
        ],
      },
    ],
  },
  {
    number: 10,
    name: 'Phase 2 — Pattern Reinforcement',
    description: 'Deepen patterns with variations (+110 problems).',
    categories: [
      {
        id: 'phase2-arrays-hashing',
        name: 'Arrays & Hashing (+12)',
        color: 'bg-blue-50 border-blue-200',
        problems: [
          {
            id: '93',
            title: 'Majority Element',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '94',
            title: 'Majority Element II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '95',
            title: 'Find All Numbers Disappeared in Array',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '96',
            title: 'Subarray Sum Equals K',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '97',
            title: 'Continuous Subarray Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '98',
            title: 'Longest Harmonious Subsequence',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '99',
            title: 'Degree of an Array',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '100',
            title: 'Find Duplicate Number',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '101',
            title: 'Set Matrix Zeroes',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '102',
            title: 'Spiral Matrix',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '103',
            title: 'Rotate Image',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '104',
            title: 'Sort Colors',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-sliding-window',
        name: 'Sliding Window (+10)',
        color: 'bg-amber-50 border-amber-200',
        problems: [
          {
            id: '105',
            title: 'Maximum Average Subarray I',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '106',
            title: 'Fruit Into Baskets',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '107',
            title: 'Longest Subarray of 1s After Deleting One',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '108',
            title: 'Binary Subarrays With Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '109',
            title: 'Subarrays With K Different Integers',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '110',
            title: 'Minimum Window Substring (revisit)',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '111',
            title: 'Sliding Window Maximum (revisit)',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '112',
            title: 'Grumpy Bookstore Owner',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '113',
            title: 'Longest Continuous Subarray With Absolute Diff ≤ Limit',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '114',
            title: 'Count Number of Nice Subarrays',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-binary-search',
        name: 'Binary Search (+10)',
        color: 'bg-green-50 border-green-200',
        problems: [
          {
            id: '115',
            title: 'First Bad Version',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '116',
            title: 'Find Peak Element',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '117',
            title: 'Search a 2D Matrix',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '118',
            title: 'Search in Rotated Sorted Array II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '119',
            title: 'Find First and Last Position',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '120',
            title: 'Capacity to Ship Packages',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '121',
            title: 'Split Array Largest Sum',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '122',
            title: 'Median of Two Sorted Arrays (revisit)',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '123',
            title: 'Kth Smallest in Sorted Matrix',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '124',
            title: 'Minimum Number of Days to Make Bouquets',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-stack',
        name: 'Stack (+8)',
        color: 'bg-red-50 border-red-200',
        problems: [
          {
            id: '125',
            title: 'Remove All Adjacent Duplicates',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '126',
            title: 'Asteroid Collision',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '127',
            title: 'Online Stock Span',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '128',
            title: 'Largest Rectangle in Histogram',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '129',
            title: 'Basic Calculator II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '130',
            title: 'Simplify Path',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '131',
            title: 'Decode String',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '132',
            title: 'Remove K Digits',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-linked-list',
        name: 'Linked List (+8)',
        color: 'bg-indigo-50 border-indigo-200',
        problems: [
          {
            id: '133',
            title: 'Intersection of Two Linked Lists',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '134',
            title: 'Palindrome Linked List',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '135',
            title: 'Swap Nodes in Pairs',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '136',
            title: 'Reverse Nodes in k-Group',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '137',
            title: 'Copy List with Random Pointer',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '138',
            title: 'Flatten Multilevel Doubly Linked List',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '139',
            title: 'Rotate List',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '140',
            title: 'Partition List',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-trees',
        name: 'Trees (+15)',
        color: 'bg-teal-50 border-teal-200',
        problems: [
          {
            id: '141',
            title: 'Binary Tree Right Side View (revisit)',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '142',
            title: 'Construct Binary Tree from Preorder & Inorder',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '143',
            title: 'Construct Binary Tree from Inorder & Postorder',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '144',
            title: 'Path Sum II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '145',
            title: 'Path Sum III',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '146',
            title: 'Binary Tree Maximum Path Sum',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '147',
            title: 'Kth Smallest in BST',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '148',
            title: 'Validate BST',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '149',
            title: 'Convert Sorted Array to BST',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '150',
            title: 'Populating Next Right Pointers',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '151',
            title: 'Serialize/Deserialize (revisit)',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '152',
            title: 'House Robber III',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '153',
            title: 'Delete Node in BST',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '154',
            title: 'Trim BST',
            difficulty: 'Easy',
            completed: false,
            phase: 2,
          },
          {
            id: '155',
            title: 'Recover BST',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-backtracking',
        name: 'Backtracking (+8)',
        color: 'bg-orange-50 border-orange-200',
        problems: [
          {
            id: '156',
            title: 'Letter Combinations of Phone Number',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '157',
            title: 'Generate Parentheses',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '158',
            title: 'Combination Sum II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '159',
            title: 'Permutations II',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '160',
            title: 'Restore IP Addresses',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '161',
            title: 'Word Search II',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '162',
            title: 'Beautiful Arrangement',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '163',
            title: 'Sudoku Solver',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-heap',
        name: 'Heap (+6)',
        color: 'bg-pink-50 border-pink-200',
        problems: [
          {
            id: '164',
            title: 'K Closest Points to Origin',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '165',
            title: 'Reorganize String',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '166',
            title: 'Furthest Building You Can Reach',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '167',
            title: 'Find K Pairs with Smallest Sums',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '168',
            title: 'IPO',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '169',
            title: 'Smallest Range Covering Elements',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-greedy',
        name: 'Greedy (+6)',
        color: 'bg-lime-50 border-lime-200',
        problems: [
          {
            id: '170',
            title: 'Candy',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '171',
            title: 'Minimum Number of Arrows to Burst Balloons',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '172',
            title: 'Queue Reconstruction by Height',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '173',
            title: 'Task Scheduler (revisit)',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '174',
            title: 'Wiggle Subsequence',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '175',
            title: 'Remove Covered Intervals',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-dp',
        name: 'Dynamic Programming (+15)',
        color: 'bg-cyan-50 border-cyan-200',
        problems: [
          {
            id: '176',
            title: 'Target Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '177',
            title: 'Partition Equal Subset Sum',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '178',
            title: 'Best Time to Buy/Sell Stock with Cooldown',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '179',
            title: 'Best Time to Buy/Sell Stock with Fee',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '180',
            title: 'Longest Palindromic Substring',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '181',
            title: 'Palindromic Substrings',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '182',
            title: 'Distinct Subsequences',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '183',
            title: 'Interleaving String',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '184',
            title: 'Burst Balloons',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '185',
            title: 'Maximum Profit in Job Scheduling',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '186',
            title: 'Delete and Earn',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '187',
            title: 'Count Square Submatrices',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '188',
            title: 'Stone Game',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '189',
            title: 'Russian Doll Envelopes',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '190',
            title: 'Arithmetic Slices',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
      {
        id: 'phase2-graphs',
        name: 'Graphs (+12)',
        color: 'bg-violet-50 border-violet-200',
        problems: [
          {
            id: '191',
            title: 'Rotting Oranges',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '192',
            title: 'Walls and Gates',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '193',
            title: 'Surrounded Regions',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '194',
            title: 'Redundant Connection',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '195',
            title: 'Evaluate Division',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '196',
            title: 'Cheapest Flights Within K Stops',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '197',
            title: 'Minimum Height Trees',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '198',
            title: 'Word Ladder (revisit)',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '199',
            title: 'Reconstruct Itinerary',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '200',
            title: 'Accounts Merge',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
          {
            id: '201',
            title: 'Critical Connections',
            difficulty: 'Hard',
            completed: false,
            phase: 2,
          },
          {
            id: '202',
            title: 'Shortest Path in Binary Matrix',
            difficulty: 'Medium',
            completed: false,
            phase: 2,
          },
        ],
      },
    ],
  },
];

export default problemsData;
